export const NAV_ITEMS = [
  {
    id: "command-center",
    path: "/dashboard",
    label: "Command Center",
    shortLabel: "Dashboard",
    description: "Fast overview of threat posture and analyst priorities.",
  },
  {
    id: "live-monitoring",
    path: "/live-monitoring",
    label: "Live Monitoring",
    shortLabel: "Live Monitoring",
    description: "Real-time traffic visibility across the monitored network.",
  },
  {
    id: "alerts",
    path: "/alerts",
    label: "Alerts",
    shortLabel: "Alerts",
    description: "Triage recent alerts and mark acknowledged events.",
  },
  {
    id: "suspicious-queue",
    path: "/suspicious-queue",
    label: "Suspicious Queue",
    shortLabel: "Suspicious Queue",
    description: "Decision-focused queue for suspicious and active detections.",
  },
  {
    id: "incidents",
    path: "/incidents",
    label: "Incidents",
    shortLabel: "Incidents",
    description: "Correlated incidents, timelines, and analyst notes.",
  },
  {
    id: "hosts",
    path: "/hosts",
    label: "Hosts",
    shortLabel: "Hosts",
    description: "Inspect monitored hosts and review IP-level behavior.",
  },
  {
    id: "actions",
    path: "/actions",
    label: "Actions",
    shortLabel: "Actions",
    description: "Containment actions, blocked IPs, and isolation state.",
  },
  {
    id: "system-status",
    path: "/system-status",
    label: "System Status",
    shortLabel: "System Status",
    description: "Operational health for AI, API, and platform services.",
  },
  {
    id: "security-tools",
    path: "/security-tools",
    label: "Security Tools",
    shortLabel: "Security Tools",
    description: "Reserved route for future enrichment and analyst tooling.",
  },
  {
    id: "pentest-console",
    path: "/pentest",
    label: "Pentest Console",
    shortLabel: "Pentest",
    description: "AI-powered penetration testing with Nmap scanning.",
  },
  {
    id: "activity-timeline",
    path: "/activity-timeline",
    label: "Activity Timeline",
    shortLabel: "Timeline",
    description: "Centralized log of all system events — pentest, auto-response, alerts.",
  },
];
